require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'

Cucumber::Rake::Task.new(:features) do |t|
  t.profile = 'default'
end

desc 'Build frank'
task :build do
    puts "Building frank..."
    sh 'frank build'
end

task :default => [:build, :features]
